### ISSUE TITLE
seas in hierarchies box

### ISSUE THREAD

**Issue by gagecarto** [jmerkle1/Migration-Mapper#11]
In app 5, when you include seas in the “There are multiple hierarchies…” box, you get an error that says "seeasons" not found. If you don't put seas in that box, all works fine.

**Comment by gagecarto** [comment]
@jmerkle1 - I was digging into this and found "seeasons" in the CalcPopUse script line below.
https://github.com/jmerkle1/Migration-Mapper/blob/main/app5_merging/wmiScripts/CalcPopUse.R#L133

Should I just change this string to "seasons"?

**Comment by jmerkle1** [comment]
Yes, i think so. If that's the only place it is written that way, it is for sure a typo. thanks!
