### ISSUE TITLE
add all parameters to metadata.csv output

### ISSUE THREAD

**Issue by gagecarto** [jmerkle1/Migration-Mapper#12]
Make sure the metadata csv that is spit out has ALL migration mapper parameters in there, so it can be recorded.

**Comment by gagecarto** [comment]
@jmerkle1 - I am looking into this comment from the Google form.. Do you know if this is in reference to the popUse, footprint or runUD metadata?

**Comment by jmerkle1** [comment]
This would be any of the params in the Calc. functions (depending on the method chosen) in app 4, as well as the params from CalcPopUse and CalcPopFootprint function in app 5.

**Comment by gagecarto** [comment]
Metadata is now written for each season processed in app4. These are stored in the metadata and look like below
`udParams<-data.frame(configOptions$udConfigOptions)
   write.csv(udParams, file=paste0(metadataFolder,"/",seqName,"_udParams.csv"), row.names = FALSE)`
![image](https://user-images.githubusercontent.com/5776766/179299423-d3743276-5d96-46cd-9b37-0d060a30c527.png)

Metadata is also written for popuse and popfootprint calcs. These are stored alongside the popuse and popfootprint metadata files
`popFootprintParams<-data.frame(configOptions$popConfigOption)
  write.csv(popFootprintParams, file=paste0(footprintsMergedFolder,"/",mergeName,"_popFootprintParams.csv"), row.names = FALSE)`
`popUseParams<-data.frame(configOptions$popConfigOption)
  write.csv(popUseParams, file=paste0(popUseFolder,"/",mergeName,"_popUseParams.csv"), row.names = FALSE)`
![image](https://user-images.githubusercontent.com/5776766/179299781-96803f40-6b7a-447a-ab6f-65c2010d6707.png)
