### ISSUE TITLE
Still crashing after identifying dates due to duplicated columns (e.g., Speed)

### ISSUE THREAD

**Issue by jmerkle1** [jmerkle1/Migration-Mapper#14]
Need some better column handlers in case users submit data with same column names that MM uses. Had an example where it crashed with a column named "speed" and a column named "dt".

**Comment by gagecarto** [comment]
fixed here 
https://github.com/jmerkle1/Migration-Mapper/commit/8556d9780db8786f2469a4f1c7dc018784dbc967
