### ISSUE TITLE
Better delete warning message in App4

### ISSUE THREAD

**Issue by gagecarto** [jmerkle1/Migration-Mapper#2]
From the comment below, add more information about exactly what will be deleted when this warning message is displayed. 

_App 4: Can the warning message (i.e., there are already files in your ... older. would you like to deleted...") in App 4 (below) be more specific? I can imagine folks will commonly try multiple methods. For example a BBMM and then a FMV BBMM or a line buffer… What are the implications of clicking ‘Yes delete and reprocess’ ? What data are being deleted and reprocessed? If you click ‘No, don’t delete’ does that mean you are making new files with a new name or canceling the export? The user can try different options and figure it out, but more direction/information here would be beneficial._

**Comment by gagecarto** [comment]
@jmerkle1 

When someone reprocesses a sequence the footprint folder is emptied for that particular sequence. 

Here's the new messages I am thinking of using. Does this seem a bit more descriptive? 

             paste0("It looks like footprints were previously calculated for ",seqName,'. Would you like to delete these files and reprocess?' ),

**Comment by jmerkle1** [comment]
looks good. perhaps add 'footprints and UDs" instead of just 'footprints'
